### ISSUE TITLE
Comment Code

### ISSUE THREAD

**Issue by IsaacMorris1980** [MoneyFox/MoneyFox#1400]
@NPadrutt  Should we comment the code to make it easier for new contributors to understand what the code does?

it would have helped me and then i would not have to ask so many questions because i got lost trying to find out where items get initialized,  what some functions do etc.

**Comment by NPadrutt** [comment]
I think improving the experience for new developers is a great idea! 
Maybe the question is, if code comments are the best way to achieve this, since they are always a mixed bag. They often introduce redundancy and are prone to not being updated when the code changes, therefore adding more confusion than support.

To help people start I think a better documentation would help a lot too. Currently the documentation is very scarce and since it hosted on our confluence contribution is not easy possible. I think about moving it to the wiki here, so that everything is in a central place.

Do you have an concrete example where you struggled? Then we can decide if it makes most sense to refactor the code, rename the methods, add code comments, or add a documentation.

**Comment by cloudstalker** [comment]
Yeah I do think the more detailed documentation is the way to go since ppl with some coding experience can understand the code but maybe not the logics behind (appreciate the variable/function naming at the moment to me they are quite straightforward).

**Comment by IsaacMorris1980** [comment]
@NPadrutt i can see what you mean, however as you know i have had to ask you alot of questions some i think were valid and some after your answer had me saying duh and wondering why i needed to ask the question in the first place(I know it was because i  was so focused on what i was trying to do that i got lost in the code and there was nothing to orient on to get my bearings)

**Comment by NPadrutt** [comment]
What would have helped you more: code comments or some high level diagramms how things work?

Besides: none of the questions I can remember stroke me as especially unjustified.

**Comment by IsaacMorris1980** [comment]
@NPadrutt  high level diagrams would help more then code comments

**Comment by NPadrutt** [comment]
@IsaacMorris1980 @cloudstalker  do you have any concrete points of documentation who would have help you starting?

**Comment by IsaacMorris1980** [comment]
@NPadrutt   what would have helped was a relational map of items.  or inheritance map. i kept trying to find where things originated from so i could find where changes might be necessary.

**Comment by NPadrutt** [comment]
I thibk for most of these things are quite helpful tools in visual studio and resharper. For example you can search for implementing classes of an interface. Therefore this is closed.
That being saied, I still try to figure out a way to document important decisions without adding a lot of redundancy to the code. Also if something if not clear or difficult to understand feel free to hit me up for example in slack so that we can make it easier or add some description.
