### ISSUE TITLE
Registration failed for UWP

### ISSUE THREAD

**Issue by snehansh** [MoneyFox/MoneyFox#1547]
**Describe the bug**
Getting the following error:

`DEP0700: Registration of the app failed. [0x80073CFB] The current user has already installed a packaged version of this app. An unpackaged version cannot replace this. The conflicting package is 57598ApplySolutionsSoftwa.MoneyFox and it was published by CN=071307B1-B0E3-434A-AD0E-FFF714A7245C.	MoneyFox.Uwp`

**To Reproduce**
1. Open the solution in VS2019.
2. Set `MoneyFox.Uwp (Universal Windows)` as the start project.
3. Run on `Local Machine`.

**Comment by NPadrutt** [comment]
I assume that you have the version from the store installed. Since the project in the store is associated with the store they have windows see's them as identically which leads the error ( probably it asked you to replace the installed version which you assumingly denied). To have both side by side you would have to associate the package with another ID. For that you would have to have a developer account though.

**Comment by NPadrutt** [comment]
Maybe we can use a beta assosciation in the repository and only resign it in the CI / CD pipeline. That would make it a lot more comfortable..

**Comment by snehansh** [comment]
Thanks @NPadrutt  for the quick response. I uninstalled the app from store and ran again. It worked!
