### ISSUE TITLE
Change Theme dynamically without restart

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#1888]
**Describe the bug**
When the device theme changes, the app has to be restarted to apply the new theme. This should happen automatically.

**Comment by kg8z** [comment]
@NPadrutt - I can take this one. It looks like the problem on Android (and likely iOS, though I haven't tested yet) is with the explicit setting of the theme (Current.UserAppTheme = xxx) in App.xaml.cs. When the theme is explicitly set in code the RequestedThemeChanged event is no longer fired when the theme is changed in the O/S. I commented out both the setting of UserAppTheme and registration of the event handler and the app automatically changed when I updated the O/S theme.  Apparently, you don't need to handle the event if all you want to do is have the app match the O/S theme.

**Comment by NPadrutt** [comment]
@kg8z  nice! you are assigned.

The question then might be, if we only offer the automatic switch based on the current theme, which is the same as we have on windows at the moment. Is there actually a situation where you have your Device Theme on Dark for example, but you want your application to use the light theme?

**Comment by kg8z** [comment]
@NPadrutt - Good point. I could add a setting that allows the user to choose Light, Dark, or System Default. The first two would force the app into the theme permanently while the last mirrors the O/S. Let me know if you think this would be useful and I’ll add it for all 3 platforms.

**Comment by NPadrutt** [comment]
For the moment I would tend to go for the automatic only route. If you get that to work properly on the mobile platforms I think we could remove the other options. Maybe create a separate commit for removing those, then we could revert quickly in case of there is a lot of feedback that setting the theme separatly is wished by users.

**Comment by kg8z** [comment]
Sounds good. Thanks.

**Comment by kg8z** [comment]
@NPadrutt  - After reviewing the code further I wanted to confirm a few things before moving forward...

The current functionality of the app always uses the O/S theme setting during startup with this code:
            Current.UserAppTheme = Current.RequestedTheme != OSAppTheme.Unspecified
                ? Current.RequestedTheme
                : OSAppTheme.Dark;

Because Current.RequestedTheme is not set in the app it always defaults to the O/S theme. There is currently no mechanism for the end user to explicitly override the app theme to force it to Light/Dark; it always follows the O/S. The problem at the moment is the event handler to capture O/S theme changes real-time (Current.RequestedThemeChanged += ...) is not fired because the code that sets the theme initially breaks the event handler. Because the event handler doesn't fire, the user must close and rerun the app to have it reflect O/S theme changes (problem reported in this issue). If I simply remove the code that sets UserAppTheme and the registration of the event handler the app will mirror the O/S theme and update immediately when it's changed. This would be the "automatic only route" you mentioned and behaves exactly as it does today with the exception of theme changes updating within a session instead of having to rerun the app.

If there's interest in allowing the user to override the O/S theme I could add a new setting that defaults to "Android/iOS/Windows Theme" but also has options for Light or Dark so the user can explicitly set the theme (saving the selected value in LocalSettings so it persists across sessions). The app would continue to behave the same way it does today unless the user manually changes the new setting to Light or Dark.

I want to confirm that my understanding is correct because your comments about removing the other options leads me to believe there's some current setting to explicitly set the theme in the app that I'm missing. None of my code exploration or testing uncovered this, but perhaps I'm missing something.

Sorry for the lengthy dissertation but I want to make sure we're in sync. If you're in agreement, I can do the following:

**Commit #1**
App continues to mirror O/S theme but apply fix that allows changes within a session

**Commit #2**
New setting to allow user to choose a specific theme and override the O/S

Is it OK for Commit #2 to be part of this issue or should it be a separate enhancement request? The issue as it stands today is really about the fix in Commit #1.

**Comment by kg8z** [comment]
@NPadrutt  - After a bit of tinkering, I'm not sure the option to toggle themes at runtime (Commit #2 above) is going to be viable. At least for Windows, the RequestedTheme property can only be set in the Application constructor. Attempting to call it once the UI is active raises a NotSupportedException exception. There's a hack that involves setting the RequestedTheme on the root XAML window but the minimize/maximize/close buttons aren't affected and remain set to the O/S theme (see screenshot below; looks bizarre). The only practical approach I see to allow the user to override the O/S theme would require them to close and rerun the app, which seems like a poor UX. Not sure if this same limitation exists on Android/iOS, but this now has me questioning the merits of the enhancement. Perhaps we should just stick to fixing the original issue (Commit #1) where the app continues to mirror the O/S theme but having it update without a restart. Let me know what you think.

<img width="952" alt="WindowTheme" src="https://user-images.githubusercontent.com/81488531/156102610-add19478-a149-47f2-8d2e-21f75c5f5c1c.png">

**Comment by NPadrutt** [comment]
hey @kg8z 
yeah the fact, that you only can set the theme on startup on windows was the reason why I removed the option to set the theme directly from the app when I migrated to WinUI, since the solution we used in UWP didn't work anymore. As you already said, the option with setting the theme on the XAML Root is pretty messy and only works halfway.

That was why I figured we go the same route on mobile as well: always use the device theme with an automatic switch and remove the options to set the theme directly on mobile. My guess is, that n the desktop version shouldn't be any changes necessary with that.

**Comment by kg8z** [comment]
Got it. That makes sense. You're correct that no changes are necessary for the desktop version. I'll update the mobile apps to follow the device theme with automatic switch. Thanks for the details.

**Comment by kg8z** [comment]
@NPadrutt  - I'm having a tough time getting the iOS project to build using my Mac. I've installed XCode and the necessary components (e.g. Xamarin.iOS) on the Mac and have been able to pair it with VS.Net running on my Windows box. However, when I try to run the project the error "Could not find any available provisioning profiles for iOS" is returned.  The signing identity under iOS Bundle Signing shows "Unknown (Apple Development: Nino Pandrutt (RHCXB7MFH3)" and the provisioning profile shows "Unknown (MoneyFox Development 2020)". Enabling Automatic Provision appears to need a paid Apple Developer account. Do you know if there's a way for me to test iOS builds without having to pay for a subscription?

**Comment by NPadrutt** [comment]
Aaah, right. I have to add you as developer on the devloper platform of apple I guess so that you can download the developer provisioning profile. Can you give me your appleid?

**Comment by kg8z** [comment]
@NPadrutt - Phew. I figured I was doing something wrong. The appleid I'll be using for development is pandamaximus@icloud.com.

**Comment by NPadrutt** [comment]
fixed with PR #2239

**Comment by NPadrutt** [comment]
@kg8z  no no. it's just a bit complicated with Apple. Especially when it is about working in an Open Source manner on a project.
You should have got an invitation from apple developer.

**Comment by kg8z** [comment]
@NPadrutt  - Awesome. I received the invitation for the Apple Developer Program. Will get that going so I can start testing my changes on iOS. No more excuses! :-) Thanks!

**Comment by NPadrutt** [comment]
@kg8z let me know if it works. Otherwise I might have to tweak some settings still.

**Comment by kg8z** [comment]
@NPadrutt  - I certainly got further along. It's giving this error when I switched to Automatic Provisioning to force it to link to my Apple Developer account:
<img width="579" alt="AppleError" src="https://user-images.githubusercontent.com/81488531/157582833-12800a0d-2b7b-4e75-9a74-41784ade92a6.png">
:

**Comment by NPadrutt** [comment]
@kg8z  alright. next try. can you try again?

**Comment by kg8z** [comment]
Unfortunately, it's still returning the same error:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/81488531/158035004-c1de0c6d-ee62-4278-89ce-9cd043f2988e.png">

**Comment by NPadrutt** [comment]
@kg8z  mmh.. that is interessting. Can it be that visual studio is trying to create a new profile instead of using the existing development one? 
I'll see if I can find anything more on this. But it seems that it is quite difficult to set that up in a way that it's easy to share those for open source projects, aka don't make the certificate used to create those public.

**Comment by kg8z** [comment]
@NPadrutt  - I don't know if this makes a difference, but the Provisioning Profile defaults to "Unknown (MoneyFox Development 2020)" when I pull the project file from GitHub:
<img width="774" alt="ProjectBundleSigningDefault" src="https://user-images.githubusercontent.com/81488531/158292756-14f46e2f-e9b5-49b3-bd39-69c2a172b55c.png">

But when I click the Manage Accounts option it shows the MoneyFox Development 2020 profile has expired and only the MoneyFox Distribution 2021 as being active:
<img width="467" alt="ProvisioningProfiles" src="https://user-images.githubusercontent.com/81488531/158293318-9a73ed39-86b3-415a-990a-3d721cb0af1d.png">

Is it possible we need to generate a new development profile for 2022? Sorry I'm not more help here.

**Comment by NPadrutt** [comment]
I created a new development certificate. Maybe that works. Otherwise we can see if I can send you the provisioning profile and certificate for development so you can install it manually. That might actually be the "cleanest" solution.

**Comment by kg8z** [comment]
Great. I'm going to be away for the next week or two but will see if the new dev certificate works when I get back. Thanks.

**Comment by NPadrutt** [comment]
@kg8z  alright. enjoy your time :)

**Comment by kg8z** [comment]
Hi @NPadrutt  - The new "MoneyFox Development 2022" certificate did  the trick. I was able to download it and successfully compile/test the iOS app. Now I don't have an excuse to omit iOS testing from my PR's. ;-)
