### ISSUE TITLE
Windows broken

### ISSUE THREAD

**Issue by hokkasenola** [MoneyFox/MoneyFox#2263]
Android version was updated yesterday. Now it made something and windows is not working anymore. (using android 11 & win 11)

![image](https://user-images.githubusercontent.com/102957350/161518133-53107791-50bb-4a2b-80e8-c2a523febfe0.png)

**Comment by NPadrutt** [comment]
hey @hokkasenola 
Thanks for the report. It seems the appropriate windows version was not correctly published.
I update this issue when the publish was successful.

In the future we have to deploy removal of db fields better.

**Comment by NPadrutt** [comment]
hey @hokkasenola 
as an update: the submission is in certification since yesterday, but for some reason it seems that it takes longer. I'll keep you updated on this when I hear something.

**Comment by NPadrutt** [comment]
Due to the current rather glacial pace of the Microsoft Store i submitted a new updated to Android and iOS that should fix the compatibility issues from that side. 
@hokkasenola Once you updated your mobile app and launched it, so that it uploaded a new backup the windows version  should work again as well. In case the error still persist you could try to manually download the backup via the backup menu.
Could you give it a try?

**Comment by hokkasenola** [comment]
Yes! Now it is working as expected. Lightning fast action. There is many many companies that should take a look and learn. (for example every phone manufacturer)
