### ISSUE TITLE
The ability to change account properties after creation

### ISSUE THREAD

**Issue by kres0345** [MoneyFox/MoneyFox#2546]
**Is your feature request related to a problem? Please describe.**
Right now, as far as I know, on mobile I can't edit account information, for example, change the name or whether it is to be excluded from the balance.

**Describe the solution you'd like**
I think it's intuitive for the user to be able to long-press an account in the account overview, to open up the account creation modal.

**Describe alternatives you've considered**
If it isn't technically possible to modify account properties, then cloning the account activity to a new account would be acceptable imo.

**Additional context**
Also, I don't think it's possible to remove accounts on mobile.

**Comment by NPadrutt** [comment]
There is such a functionality, but there are some issues with it. It uses a SwipeView in the Accountlist (you get there from the dashboard -> All Accounts. But with the migration to .net maui it seems that the swipe view control on Android has an issue and does not work. There seems to be a fix coming soon..
The other issue is, that when you click on edit it will make a second navigation to the payment list, since it also recognises the tap.
Thirdly, there seems to be an issue with the binding that is from the migration.

I'm not opposed to go for a long press instead of the swipe view. For the moment we would have to handle this ourselfes since maui doesn't offer that and right click is only coming to desktop with .net 7. In case you want to give this a go, I found some guides that might point you in the right direction.

**Comment by NPadrutt** [comment]
I actually had a quick look and was able to fix most of the issue. PR is open: #2547 
On iOS that is. For Android I think we have to wait till Microsoft rolls out their fix.

but the long press feature could still be interesting for the dashboard page in case you want to have a look

**Comment by NPadrutt** [comment]
The SwipeView does work on android as well now. Therefor I close this issue.
