### ISSUE TITLE
When on a paymentlist of a account, lock the charged account for transfers

### ISSUE THREAD

**Issue by sethbartlett** [MoneyFox/MoneyFox#984]
Currently when you do a new transfer, there are 2 separate lists of accounts and a "Charged" Account and a "Target" Account. The "Charged" account shouldn't be a list and shouldn't be editable, it should just be the current account you are on, locked and not editable. Also, at the same time, maybe the "Transfer" button shouldn't exist period outside of an account, so a user would have to actually go into an account to transfer money (Which seems to make the most sense), rather than just transferring from the main page.

**Comment by NPadrutt** [comment]
Wouldn't it be better if the charged account is just removed from the target accoutn list? so that you can't transfer to the same account? as in #952 
I'm not sure placing the transfer button in the selected account only would make the user experience better. It makes the option more hidden in the contrary to now.

**Comment by sethbartlett** [comment]
Hmm, so maybe 2 different paths here. When you hit Transfer on the main page (No account selected), you can pick whatever you want. But when you are in an Account and hit Transfer, lock the "Charged" account, because you are obviously wanting to transfer money out of that account?

**Comment by NPadrutt** [comment]
Given the age I close this. If this is still wished, please reopen.
